# Generated by Django 5.2.5 on 2025-09-04 08:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0002_rayon_contenir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('idStatus', models.AutoField(primary_key=True, serialize=False)),
                ('libelleStatus', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='dateFab',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='produit',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='monApp.status'),
        ),
    ]
