# Generated by Django 5.2.5 on 2025-09-29 09:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_status_produit_datefab_produit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenir',
            name='quantite',
        ),
        migrations.AddField(
            model_name='contenir',
            name='Qte',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nomCat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contenir',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenir_produit', to='monApp.produit'),
        ),
        migrations.AlterField(
            model_name='contenir',
            name='rayon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenir_rayon', to='monApp.rayon'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_categorie', to='monApp.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='dateFab',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='produit',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_status', to='monApp.status'),
        ),
        migrations.AlterField(
            model_name='rayon',
            name='nomRayon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='libelleStatus',
            field=models.CharField(max_length=100),
        ),
    ]
