# Generated by Django 5.2.5 on 2025-10-14 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0004_remove_contenir_quantite_contenir_qte_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contenir',
            unique_together={('produit', 'rayon')},
        ),
    ]
