from django.urls import path
from . import views
from django.views.generic import *

urlpatterns = [
    #path('home',views.home ,name='home'), # Par defaut 
    #path('home/<str:param>',views.home ,name='home'),
    path("home", views.HomeView.as_view(), name="home"),
    path("home/<str:param>", views.HomeView.as_view(), name="home_param"),
    # path("contact/<str:param>", views.ContactView.as_view()),
    path("about/<str:param>", views.AboutView.as_view(), name="about_param"),
    path("contact", views.ContactView, name="contact"),
    path("about", views.AboutView.as_view(), name="about"),
    #path("about", views.about, name="about"),
    path("products", views.ProduitListView.as_view(), name="lst_prdts"),
    path("product", views.ProduitCreateView.as_view(), name="crt_prdt"),
    path("products/<pk>/update/",views.ProduitUpdateView.as_view(), name="prdt_chng"),
    path("products/<pk>/delete/",views.ProduitDeleteView.as_view(), name="dlt_prdts"),
    path("products/<pk>", views.ProduitDetailView.as_view(), name="dtl_prdt"),
    path("status/<pk>", views.StatusDetailView.as_view(), name="dtl_status"),
    path("rayons/<pk>", views.RayonDetailView.as_view(), name="dtl_rayon"),
    path("categories", views.CategorieListView.as_view(), name="lst_ctds"),
    path("categories/<pk>", views.CategorieDetailView.as_view(), name="dtl_ctd"),
    path("categorie", views.CategorieCreateView.as_view(), name="crt_cat"),
    path("categories/<pk>/update/",views.CategorieUpdateView.as_view(), name="cat_chng"),
    path("categories/<pk>/delete/",views.CategorieDeleteView.as_view(), name="dlt_cat"),
    path("rayons", views.RayonListView.as_view(), name="lst_rayons"),
    path("rayon", views.RayonCreateView.as_view(), name="crt_rayon"),
    path("rayons/<pk>/update/",views.RayonUpdateView.as_view(), name="rayon_chng"),
    path("rayons/<pk>/delete/",views.RayonDeleteView.as_view(), name="dlt_rayon"),
    path("status", views.StatusListView.as_view(), name="lst_status"),
    path("stat", views.StatusCreateView.as_view(), name="crt_status"),
    path("status/<pk>/update/",views.StatusUpdateView.as_view(), name="status_chng"),
    path("status/<pk>/delete/",views.StatusDeleteView.as_view(), name="dlt_status"),
    path('login', views.ConnectView.as_view(), name='login'),
    path('register', views.RegisterView.as_view(), name='register'),
    path('logout', views.DisconnectView.as_view(), name='logout'),
    path('email-sent', views.ConfirmationEmailView.as_view(), name="email-sent"),
    path('rayon/<pk>/contenir', views.ContenirCreateView.as_view(), name='cntnr-crt'),
    path('rayon/<pk>/contenir/<pkp>/update', views.ContenirUpdateView.as_view(), name='cntnr-chng'),
    path('rayon/<pk>/contenir/<pkp>/delete', views.ContenirDeleteView.as_view(), name='cntnr-dlt'),
]
